# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'cibo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  target 'ciboTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cibo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cibo-tvOS

  target 'cibo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#Also add this at the very bottom of your Podfile

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end

end

  # Temporary workaround for https://github.com/invertase react-native-firebase/issues/395
  #`rm -rf Pods/leveldb-library/port/win`

